### PR TITLE
add chex.wad to iwad list

### PR DESCRIPTION
**Pull request by eyecreate**
add chex.wad to iwad list. Should allow Chex Quest to be played.

### CODE REVIEW

**Comment by DrUm78** [comment]
Chex Quest 1 and 2 both work fine for me on classic_armv7_a7. Anyway Chex is not an IWAD but a PWAD (also it requires Doom 1, not Doom 2) so I don't see the point with this PR.

**Comment by eyecreate** [comment]
I assumed why I couldn't get it working was this, which was mentioned in parent repo issue. 
https://github.com/libretro/libretro-prboom/issues/166
If you have it working without any changes, did you use a prboom.cfg or just chex.wad and doom.wad together in directory? (I'm using 2.5 opk.)

**Comment by DrUm78** [comment]
My OPK is ONLY for the FunKey S handheld device, is that the device you use? Otherwise, it won't work as the binary inside is only compiled for armv7_7a.
And you have to understand the difference between an IWAD and a PWAD, that's important, please see the doc here:
https://docs.libretro.com/library/prboom/#loading-doom

**Comment by eyecreate** [comment]
I am using the funkey s as well as your latest funkeyos release.

**Comment by DrUm78** [comment]
So please read the Libretro doc and my instructions (at the bottom of my page: https://github.com/DrUm78/libretro-prboom/releases).

**Comment by DrUm78** [comment]
If you can't get it working **after reading the doc** (please) then come on the FunKey S discord server, I won't discuss this anymore here:
https://discord.com/invite/u84XEhqzJF

**Pull request closed without merging**
